server:
  port: 8080

spring:
  application:
    name: consul-consumer-order
  #consul注册中心地址
  cloud:
    consul:
      host: 123.57.21.92
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        heartbeat:
          enabled: true
