server:
  port: 8003

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 10.7.31.29:1111   # nginx的端口，配置转发到nacos集群
#        server-addr: localhost:8848

#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
server-url:
  nacos-user-service: http://nacos-payment-provider


python:
  django:
    url: http://123.57.21.92:8011