server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  #consul注册中心地址
  cloud:
    consul:
      host: 123.57.21.92
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        heartbeat:
            enabled: true